### ISSUE TITLE
Is the project alived? 

### ISSUE THREAD

**Issue by janckerchen** [EA31337/EA31337-classes#21]
It's amazing job for professional mql4 developer, never give up please.

What's the plant for next few months?

**Comment by kenorb** [comment]
Thanks for your support, project is still ongoing, but slow progress due to lack of funds and time. I hope to continue in the next few days, otherwise it may be delayed for few weeks. Plan for the next months is to finish EA31337-Libre as fully-working EA and implement all strategies, then long-term plan is to implement new strategies and improve existing as much as possible and add new features. There is also [EA31337 Lite](https://www.mql5.com/en/market/product/10868) version, which is closed project, but it is based on these class files in this repo, so you may consider purchasing it to support open-source Libre version which is complete refactor of Lite version.

**Comment by janckerchen** [comment]
@kenorb  Thanks your detailed explained very much. 

I  cloned the project,  look around codebase, try to smoke test.  but  dependencies between sub-projects there are complex . I was tangled by obscure architecture, even compilation is not easy.

For example,  I want to find  out how the OrderSend() be encapsulated, but failed. there are many variant, some of which are imcomplete.

Maybe we need a minimum viable product with kickoff doc,  let anybody to check  easly.

**Comment by kenorb** [comment]
@janckerchen 

Compilation should be simple, copy/clone EA31337-classes and EA31337-strategies dirs into platform's _Include_ folder, place EA31337-Libre in platform's Experts folder, the MQL4 compilation should be smooth (any class file should be compiled successfully, or the main Libre mq4 or mql5 file). The code should be compatible with MQL5 also, but it may need some additional work.

Goal of Libre project is to have minimum viable product, but it may take few weeks to make it working.

In _MetaEditor_ you can find the right methods by jumping into definition (_Go To Definition_ or _Alt-G_), sometimes it may fail.

OrderSend() is defined in `Order.mqh`, but it needs some work for MQL5, it may work for MQL4, but I haven't tested it yet.

**Comment by janckerchen** [comment]
Unfortunately I encounter many compile errors like this :

<img width="644" alt="screenshot of parallels desktop 2017 4 24 16 35" src="https://cloud.githubusercontent.com/assets/68181/25328945/493c2c76-290c-11e7-9002-4262459475a6.png">

it seams Libre project outdated.  for example : 

```
void OnTick() {
  if (!session_initiated) return;

  // Check the last price tick change.
  double last_ask = market.GetLastAsk();
  double last_bid = market.GetLastBid();
  double tick_change = fmax(Convert::GetValueDiffInPips(market.GetAsk(), last_ask, True), Convert::GetValueDiffInPips(market.GetBid(), last_bid, True));

  if (tick_change >= MinPipChangeToTrade) {
    MqlTradeRequest deal;
    MqlTradeResult result;
    if (strategies.Signal(deal)) {
      trade.NewOrder(deal, result);   <----  looks here!
    }
  }
}
```
There is no NewOrder function in Trade.mqh.

**Comment by janckerchen** [comment]
Update  EA31337-classes and EA31337-strategies to edge commit,  compile EA31337-Libre again:
<img width="654" alt="screenshot of parallels desktop 2017 4 24 17 30" src="https://cloud.githubusercontent.com/assets/68181/25330952/06b79d92-2914-11e7-8d44-0485db4d9c0d.png">


EA31337-Libre version seems  fall behind  two core projects.

**Comment by kenorb** [comment]
@janckerchen All class files should compile fine as per [CI test](https://travis-ci.org/EA31337/EA31337-classes/builds/212775679), it fails only with the older compiler. Also here at [Appveyor](https://ci.appveyor.com/project/kenorb/ea31337-classes/history), but the tests needs some work. Problems is with Libre code which has not been updated recently after some changes in classes (some methods were renamed), so it needs more work. I'll have a look today or tomorrow to fix the code, so it can compile.

**Comment by janckerchen** [comment]
@kenorb thanks for your  generous.   Just making Libre pass compilation is enough.

**Comment by janckerchen** [comment]
@kenorb I still trace the issue, how is it going?  I try to fix it, but lost, especially where the `NewOrder()` is.

**Comment by kenorb** [comment]
@janckerchen The `NewOrder` is in `Orders.mqh` (as you've found it). You can try to uncomment it out. It was commented probably to be able to compile  the code properly and creating the new orders needs some work, since the goal is to write the code which works in both MQL4 and MQL5 (so the code implementation is something between), currently it's focusing on compilation on MQL4, but with few improvements, it may work for MQL5. I'll be checking the code within few days, as I was working on the next Lite version recently.

**Comment by kenorb** [comment]
@janckerchen Fixed compilation errors, now it compiles fine for me. Please test, but the code could be not complete.

**Comment by janckerchen** [comment]
@kenorb  thx,   Libre has passed,  but left some slight errors in  EA31337-strategies submodule.

![screenshot of parallels desktop 2017 4 28 09 35](https://cloud.githubusercontent.com/assets/68181/25511029/edd07142-2bf6-11e7-8fcc-fc769a1be40e.png)

Maybe I should close this issue, open another one for further feedback.  I can help to fix simple problem with pull request,  or  waiting your major refactor in few days?

**Comment by kenorb** [comment]
@janckerchen You may create separate issues for each problem, may work.

The issue with NewValue() isn't easy to solve and it can be challenging. It's basically a prototype of class which aims to store the values of the indicator.

I've described the problem in more details at the following [job post](https://www.mql5.com/en/job/57191), but the developer failed to implement it since it's not straight forward.

If you manage to implement this class in order to store the values in the way it's currently designed, I'm happy to pay you a bounty.

**Comment by kenorb** [comment]
`NewValue()` has been renamed to `Add()` and can be found in `Indicator.mqh` class file. The usage and goal of the class is demonstrated in `Indicator.mq5`.

**Comment by kenorb** [comment]
If you would have any specific problems or bugs, raise a new tickets then in relevant repository, so we can solve them.
